spring:
  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    generate-ddl: false
    hibernate:
      dda-auto: none
    show-sql: true

  liquibase:
    enabled: true

logging:
  level:
    root: INFO

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: "health, info, hystrix.stream"

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false