spring:
  application:
    name: updater

server:
  port: 8081

logging:
  level:
    root: INFO

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

hystrix:
  threadpool:
    default:
      coreSize: "20"
      maxQueueSize: "500000"
      keepAliveTimeMinutes: "2"
      queueSizeRejectionThreshold: "500000"
  dashboard:
    proxy-stream-allow-list: "*"
  command:
    default:
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: "20"
      execution:
        timeout:
          enabled: "false"
        isolation:
          strategy: "THREAD"
          thread:
            timeoutInMilliseconds: "20000"

management:
  endpoints:
    web:
      exposure:
        include: "health, info, hystrix.stream"

#####################################################

update:
  abbvie:
    url: "https://www.abbvie.com/content/abbvie-dotcom/us/en/our-science/pipeline/jcr:content/pipeline.molecules.json"
  bms:
    url: "https://www.bms.com/content/bms/us/en_us/home/researchers-and-partners/in-the-pipeline/jcr:content/par/pipelinephaselisting.listing.json?page=/content/bms/us/en_us/home/researchers-and-partners/in-the-pipeline/jcr:content/par/pipelinephaselisting"