spring:
  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    generate-ddl: false
    hibernate:
      dda-auto: none
    show-sql: true

  liquibase:
    enabled: true

logging:
  level:
    root: INFO